# generated by cabal-rpm-2.0.5 --standalone
# https://fedoraproject.org/wiki/Packaging:Haskell

%global ghc_without_dynamic 1
%global ghc_without_shared 1
%undefine with_ghc_prof
%undefine with_haddock
%global without_prof 1
%global without_haddock 1
%global debug_package %{nil}

%global pkg_name stack
%global pkgver %{pkg_name}-%{version}

Name:           %{pkg_name}
Version:        2.3.1
Release:        1%{?dist}
Summary:        The Haskell Tool Stack

License:        BSD
Url:            https://hackage.haskell.org/package/%{name}
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz
Source1:        https://hackage.haskell.org/package/%{pkgver}/%{name}.cabal#/%{pkgver}.cabal
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-Cabal-devel
%if %{defined fedora} >= 31
BuildRequires:  ghc-aeson-devel
BuildRequires:  ghc-annotated-wl-pprint-devel
BuildRequires:  ghc-ansi-terminal-devel
BuildRequires:  ghc-array-devel
BuildRequires:  ghc-async-devel
BuildRequires:  ghc-attoparsec-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-base64-bytestring-devel
BuildRequires:  ghc-bytestring-devel
#BuildRequires:  ghc-casa-client-devel
#BuildRequires:  ghc-casa-types-devel
BuildRequires:  ghc-colour-devel
BuildRequires:  ghc-conduit-devel
BuildRequires:  ghc-conduit-extra-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-cryptonite-devel
BuildRequires:  ghc-cryptonite-conduit-devel
BuildRequires:  ghc-deepseq-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-echo-devel
BuildRequires:  ghc-exceptions-devel
BuildRequires:  ghc-extra-devel
BuildRequires:  ghc-file-embed-devel
#BuildRequires:  ghc-filelock-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-fsnotify-devel
BuildRequires:  ghc-generic-deriving-devel
BuildRequires:  ghc-githash-devel
BuildRequires:  ghc-hackage-security-devel
BuildRequires:  ghc-hashable-devel
#BuildRequires:  ghc-hi-file-parser-devel
#BuildRequires:  ghc-hpack-devel
BuildRequires:  ghc-hpc-devel
BuildRequires:  ghc-http-client-devel
BuildRequires:  ghc-http-client-tls-devel
BuildRequires:  ghc-http-conduit-devel
#BuildRequires:  ghc-http-download-devel
BuildRequires:  ghc-http-types-devel
BuildRequires:  ghc-memory-devel
BuildRequires:  ghc-microlens-devel
#BuildRequires:  ghc-mintty-devel
BuildRequires:  ghc-mono-traversable-devel
BuildRequires:  ghc-mtl-devel
#BuildRequires:  ghc-mustache-devel
#BuildRequires:  ghc-neat-interpolation-devel
BuildRequires:  ghc-network-uri-devel
#BuildRequires:  ghc-open-browser-devel
BuildRequires:  ghc-optparse-applicative-devel
BuildRequires:  ghc-optparse-simple-devel
#BuildRequires:  ghc-pantry-devel
BuildRequires:  ghc-path-devel
BuildRequires:  ghc-path-io-devel
BuildRequires:  ghc-persistent-devel
BuildRequires:  ghc-persistent-sqlite-devel
BuildRequires:  ghc-persistent-template-devel
BuildRequires:  ghc-pretty-devel
BuildRequires:  ghc-primitive-devel
BuildRequires:  ghc-process-devel
#BuildRequires:  ghc-project-template-devel
#BuildRequires:  ghc-regex-applicative-text-devel
#BuildRequires:  ghc-retry-devel
BuildRequires:  ghc-rio-devel
%if 0%{?fedora} >= 32
BuildRequires:  ghc-rio-prettyprint-devel
%endif
BuildRequires:  ghc-semigroups-devel
BuildRequires:  ghc-split-devel
BuildRequires:  ghc-stm-devel
BuildRequires:  ghc-streaming-commons-devel
BuildRequires:  ghc-tar-devel
BuildRequires:  ghc-template-haskell-devel
BuildRequires:  ghc-temporary-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-text-metrics-devel
BuildRequires:  ghc-th-reify-many-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-tls-devel
BuildRequires:  ghc-transformers-devel
BuildRequires:  ghc-typed-process-devel
BuildRequires:  ghc-unicode-transforms-devel
BuildRequires:  ghc-unix-devel
BuildRequires:  ghc-unix-compat-devel
BuildRequires:  ghc-unliftio-devel
BuildRequires:  ghc-unordered-containers-devel
BuildRequires:  ghc-vector-devel
BuildRequires:  ghc-yaml-devel
BuildRequires:  ghc-zip-archive-devel
BuildRequires:  ghc-zlib-devel
BuildRequires:  cabal-install > 1.18
# for missing dep 'casa-client':
BuildRequires:  ghc-base16-bytestring-devel
BuildRequires:  ghc-resourcet-devel
BuildRequires:  ghc-th-lift-devel
BuildRequires:  ghc-unliftio-core-devel
# for missing dep 'casa-types':
BuildRequires:  ghc-base16-bytestring-devel
BuildRequires:  ghc-path-pieces-devel
# for missing dep 'hi-file-parser':
BuildRequires:  ghc-binary-devel
# for missing dep 'hpack':
BuildRequires:  ghc-Glob-devel
BuildRequires:  ghc-bifunctors-devel
#BuildRequires:  ghc-infer-license-devel
BuildRequires:  ghc-scientific-devel
# for missing dep 'mustache':
BuildRequires:  ghc-cmdargs-devel
BuildRequires:  ghc-either-devel
BuildRequires:  ghc-parsec-devel
BuildRequires:  ghc-scientific-devel
BuildRequires:  ghc-th-lift-devel
# for missing dep 'neat-interpolation':
BuildRequires:  ghc-megaparsec-devel
# for missing dep 'pantry':
BuildRequires:  ghc-base-orphans-devel
BuildRequires:  ghc-contravariant-devel
BuildRequires:  ghc-digest-devel
BuildRequires:  ghc-network-devel
BuildRequires:  ghc-resourcet-devel
#BuildRequires:  ghc-rio-orphans-devel
BuildRequires:  ghc-safe-devel
BuildRequires:  ghc-syb-devel
BuildRequires:  ghc-tar-conduit-devel
BuildRequires:  ghc-th-lift-devel
BuildRequires:  ghc-th-lift-instances-devel
BuildRequires:  ghc-th-orphans-devel
#BuildRequires:  ghc-th-utilities-devel
# for missing dep 'project-template':
BuildRequires:  ghc-resourcet-devel
# for missing dep 'regex-applicative-text':
BuildRequires:  ghc-regex-applicative-devel
# for missing dep 'retry':
BuildRequires:  ghc-random-devel
# End cabal-rpm deps
%else
BuildRequires:  ghc-libraries
# for digest
BuildRequires:  zlib-devel
Requires:       gcc
Requires:       gmp-devel
BuildRequires:  cabal-install
%if %{defined fedora}
BuildRequires:  happy
%endif
%endif

%description
Stack is a cross-platform program for developing Haskell projects.
It is intended for Haskellers both new and experienced.

See haskellstack.org or the doc directory for more information.


%prep
# Begin cabal-rpm setup:
%setup -q
# no bounds in tarball
cp -bp %{SOURCE1} %{name}.cabal
# End cabal-rpm setup


%build
# Begin cabal-rpm build:
%global cabal cabal
%cabal update
%cabal sandbox init
%if 0%{?rhel}
%cabal install happy
%endif
%cabal install --only-dependencies --force-reinstalls
%ghc_bin_build
# End cabal-rpm build


%install
# Begin cabal-rpm install
%ghc_bin_install
find %{buildroot}%{_libdir} -name 'libHS%{pkgver}-*.so' -delete
rm -r %{buildroot}%{ghclibdir}
# End cabal-rpm install


%files
%license .cabal-sandbox/share/doc/*/*
# Begin cabal-rpm files:
%license LICENSE
%doc CONTRIBUTING.md ChangeLog.md README.md
%{_bindir}/%{name}
# End cabal-rpm files
%doc doc


%changelog
* Fri May  1 2020 Jens Petersen <petersen@redhat.com> - 2.3.1-1
- update to 2.3.1
- https://docs.haskellstack.org/en/stable/ChangeLog/#v231

* Tue Jul 23 2019 Jens Petersen <petersen@redhat.com> - 2.1.3.1-1
- update to 2.1.3.1
- https://docs.haskellstack.org/en/stable/ChangeLog/#v213

* Wed Jun 19 2019 Jens Petersen <petersen@redhat.com> - 2.1.1.1-1
- update to 2.1.1.1
- https://docs.haskellstack.org/en/stable/ChangeLog/#v211

* Fri Dec  7 2018 Jens Petersen <petersen@redhat.com> - 1.9.3-1
- 1.9.3 release
- https://docs.haskellstack.org/en/stable/ChangeLog/#v193

* Mon Nov 19 2018 Jens Petersen <petersen@redhat.com> - 1.9.1.1-1
- 1.9.1.1 release
- https://docs.haskellstack.org/en/stable/ChangeLog/#v1911

* Fri Oct 19 2018 Jens Petersen <petersen@redhat.com> - 1.9.1-1
- 1.9.1 release
- https://docs.haskellstack.org/en/stable/ChangeLog/#v191

* Wed Jul 25 2018 Jens Petersen <petersen@redhat.com> - 1.7.1-2
- require gcc and gmp-devel (#1)

* Sun Apr 29 2018 Jens Petersen <petersen@redhat.com> - 1.7.1-1
- update to 1.7.1
- use revised .cabal file

* Wed Feb 21 2018 Jens Petersen <petersen@redhat.com> - 1.6.5-1
- update to 1.6.5

* Sat Jan 13 2018 Jens Petersen <petersen@redhat.com> - 1.6.3-1
- update to 1.6.3

* Fri Dec  8 2017 Jens Petersen <petersen@redhat.com> - 1.6.1-1
- update to 1.6.1

* Tue Dec  5 2017 Jens Petersen <petersen@redhat.com> - 1.5.1-1
- update to 1.5.1

* Wed Mar 15 2017 Jens Petersen <petersen@redhat.com> - 1.4.0-1
- update to 1.4.0
- https://docs.haskellstack.org/en/stable/ChangeLog/#140
- for releases use 7.10.3 copr just BR ghc-libraries

* Wed Dec 28 2016 Jens Petersen <petersen@redhat.com> - 1.3.2-1
- update to 1.3.2

* Fri Dec 16 2016 Jens Petersen <petersen@redhat.com> - 1.3.0-1
- 1.3.0 release
- https://github.com/commercialhaskell/stack/releases/tag/v1.3.0

* Thu Sep 22 2016 Jens Petersen <petersen@redhat.com> - 1.2.0-1

* Sat May 21 2016 Jens Petersen <petersen@fedoraproject.org> - 1.1.2-1

* Thu May  5 2016 Jens Petersen <petersen@redhat.com> - 1.1.0-1
- update to 1.1.0

* Mon Apr 11 2016 Jens Petersen <petersen@redhat.com> - 1.0.4.3-1
- update to 1.0.4.3

* Mon Apr  4 2016 Jens Petersen <petersen@redhat.com> - 1.0.4.2-2
- require ncurses-compat-libs for F24+ to help people use upstream ghc tarballs
  (thanks Jan Synacek)

* Thu Mar 10 2016 Jens Petersen <petersen@redhat.com> - 1.0.4.2-1
- update to 1.0.4.2

* Fri Feb 26 2016 Jens Petersen <petersen@redhat.com> - 1.0.4.1-1
- update to 1.0.4.1

* Tue Jan 19 2016 Jens Petersen <petersen@redhat.com> - 1.0.2-1
- update to 1.0.2

* Fri Jan  8 2016 Jens Petersen <petersen@redhat.com> - 1.0.0-1
- update to 1.0.0

* Fri Dec 18 2015 Jens Petersen <petersen@redhat.com> - 0.1.10.1-1
- update to 0.1.10.1

* Wed Dec  9 2015 Jens Petersen <petersen@redhat.com> - 0.1.10.0-1
- update to 0.1.10.0
- build with ghc-7.10 and assume only ghc libs

* Mon Nov 30 2015 Jens Petersen <petersen@redhat.com> - 0.1.8.0-1
- 0.1.8.0

* Thu Oct 22 2015 Jens Petersen <petersen@redhat.com> - 0.1.6.0-1
- update to 0.1.6.0

* Sat Oct  3 2015 Jens Petersen <petersen@fedoraproject.org> - 0.1.5.0-1
- 0.1.5.0

* Wed Sep 02 2015 Jens Petersen <petersen@redhat.com> - 0.1.3.1-1
- update to 0.1.3.1

* Mon Jul 13 2015 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 0.1.2.0-1
- spec file generated by cabal-rpm-0.9.6.50
